# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Shared preparation actions"
description: >
  Runs multiple idividual preparation actions
inputs:
  inputs:
    python-version:
      description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset."
      required: true
  dependencies:
    description: >
      The list of SpiNNaker dependencies to check out. Space-separated
    required: true
  install:
    description: Whether to install the dependency after checking it out
    required: false
    default: "false"
  preinstall:
    description: >
      Whether to pre-install the dependencies before running the installer
    required: false
    default: "false"
  requirements-filename:
    description: The name of the requirements file
    required: false
    default: requirements.txt
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        allow-prereleases: ${{ inputs.python-version == 3.13 }}

    - name: Install Spinnaker Dependencies
      uses: ./support/actions/install-spinn-deps
      with:
        repositories: ${{ inputs.dependencies }}
        install: ${{ inputs.install }}

    - name: Run Install
      uses: ./support/actions/run-install



