# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: "Check out and install SpiNNaker dependencies"
description: >
  Checks out (and optionally installs) SpiNNaker dependencies.
inputs:
  repositories:
    description: >
      The list of SpiNNaker dependencies to check out. Space-separated
    required: true
  install:
    description: Whether to install the dependency after checking it out
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - run: |
        for repo in $DEPENDENCIES; do
          "$SPIN_GITCLONE" https://github.com/SpiNNakerManchester/$repo.git
        done
      shell: bash
      working-directory: .
      env:
        DEPENDENCIES: ${{ inputs.repositories }}
        SPIN_GITCLONE: ${{ github.action_path }}/gitclone.sh
    - run: |
        if [ $DO_INSTALL = "true" ]; then
          for repo in $DEPENDENCIES; do  
            if [ -f "$repo/setup.cfg" ]; then
              echo "::group::Installing $repo"
              pip install ./$repo
              echo "::endgroup::"
            else
              echo "::group::Setting up $repo"
                (cd $repo && exec python setup.py develop)
              echo "::endgroup::"
            fi
          done
        fi
      shell: bash
      working-directory: .
      env:
        DEPENDENCIES: ${{ inputs.repositories }}
        DO_INSTALL: ${{ inputs.install }}
