# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Lint with ruff"

description: >
  Runs the ruff check

inputs:
  python-version:
    description: The python version to use
    required: true

runs:
  using: composite
  steps:
  - run: |
      if [[ ${{ matrix.python-version}} = 3.10 ]]; then
        echo ruff check --target-version py310
        ruff check --target-version py310
      elif [[ ${{ matrix.python-version}} = 3.11 ]]; then
        echo ruff check --target-version py311
        ruff check --target-version py311
      elif [[ ${{ matrix.python-version}} = 3.12 ]]; then
        echo ruff check --target-version py312
        ruff check --target-version py312
      elif [[ ${{ matrix.python-version}} = 3.13 ]]; then
        echo ruff check --target-version py313
        ruff check --target-version py313
      elif [[ ${{ matrix.python-version}} = 3.14 ]]; then
        echo ruff check --target-version py314
        ruff check --target-version py314
      elif [[ ${{ matrix.python-version}} = 3.15 ]]; then
        echo ruff check --target-version py315
        ruff check --target-version py315
      elif [[ ${{ matrix.python-version}} = 3.16 ]]; then
        echo ruff check --target-version py316
        ruff check --target-version py316
      elif [[ ${{ matrix.python-version}} = 3.17 ]]; then
        echo ruff check --target-version py317
        ruff check --target-version py317
      elif [[ ${{ matrix.python-version}} = 3.18 ]]; then
        echo ruff check --target-version py318
        ruff check --target-version py318
      else
        echo unexpected pythn versiion ${{ matrix.python-version}}
        runn check --target-version ${{ matrix.python-version}}
      fi
    shell: bash
  
