# Copyright (c) 2021 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Note that this action (especially its requirements file) may need updating
# as different versions of matplotlib and python are released.

name: Install matplotlib
inputs:
  back-end: 
    description: Which rendering engine to use, a python module name
    required: false
    default: matplotlib.backends.backend_agg
runs:
  using: composite
  steps:
  - run: echo "MPLBACKEND=module://${{ inputs.back-end }}" >> $GITHUB_ENV
    # We want this variable to persist
    shell: bash
  - run: python -m pip install -r "$REQ_PATH"
    shell: bash
    env:
      REQ_PATH: ${{ github.action_path }}/requirements.txt
