# Copyright (c) 2021 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Note that this action may need updating as different versions of matplotlib
# and python are released.

name: Install matplotlib
inputs:
  python-version:
    description: The version of python being used
    required: true
  back-end: 
    description: Which rendering engine to use, a python module name
    required: false
    default: matplotlib.backends.backend_agg
runs:
  using: composite
  steps:
  - run: echo "MPLBACKEND=module://${{ inputs.back-end }}" >> $GITHUB_ENV
    # We want this variable to persist
    shell: bash
  - run: |
      if [ $V36 = "true" ]; then
        pip install "matplotlib < 3.4"
      else
        pip install "matplotlib"
      fi
    shell: bash
    env:
      V36: ${{ inputs.python-version == '3.6' }}
