# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: "Install Advanced Python Tools"
description: >
  Installs tooling to support advanced Python testing.
inputs:
  pylint-version:
    description: The version of pylint desired
    required: false
    default: ""
  coverage:
    description: Whether to install tools for coverage checking
    required: false
    default: "true"
  coverage-version:
    description: The version of coverage desired
    required: false
    default: ">= 6.0"
  spell-checker-implementation:
    description: >
      The packages required for the implementation of the spell checker. These
      run behind the enchant API. This may include installing a particular 
      dictionary.
    required: false
    default: "hunspell hunspell-en-gb"
runs:
  using: composite
  steps:
  - name: Install spell checker
    shell: bash
    run: source $SUPPORT_DIR/setup-spell.bash
    env:
      SPELL_PACKAGES: ${{ inputs.spell-checker-implementation }}
      SUPPORT_DIR: ${{ github.action_path }}
  - name: Upgrade Python baseline tooling
    shell: bash
    run: python -m pip install --upgrade setuptools wheel
  - name: Ensure correct version of pip
    shell: bash
    run: python -m pip install pip
  - name: Install extended Python tooling
    shell: bash
    run: |
      pip install flake8 "pylint $PYLINT_VERSION" pyenchant
      if [ $DO_COVERAGE = "true" ]; then
        pip install "coverage $COVERAGE_VERSION" coveralls
      fi
    env:
      PYLINT_VERSION: ${{ inputs.pylint-version }}
      DO_COVERAGE: ${{ inputs.coverage == 'true' }}
      COVERAGE_VERSION: ${{ inputs.coverage-version }}
