# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Run py.test"
description: |
  Runs pytest and optionally coveralls.
  Note that installing pytest and coveralls in the environment before this action is up to the caller.
  Doesn't (currently) support parallel coverage gathering.
inputs:
  tests:
    description: The name of the Python package containing the tests
    required: true
  options:
    description: Extra options to pass to pytest
    required: false
    default: ""
  coverage:
    description: Whether to do coverage
    required: false
    default: false
  cover-packages:
    description: The names of the Python packages to get coverage of.
    required: false
    default: ""
  coveralls-token:
    description: The secret token used for uploading to coveralls.io
    required: false
    default: ""
  coveralls-flag-name:
    description: >
      Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown
      in the Coveralls UI.
    required: false
    default: Unit
  coveralls-parallel:
    description: >
      Whether a matrix of jobs is being done. If they are, you'll need to add a
      finalization "build"; see 
      https://github.com/TheKevJames/coveralls-python/blob/master/docs/usage/configuration.rst
      for details. (tl;dr: coveralls --service=github --finish)
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: install pytest
      run: |
        python -m pip install pytest-timeout pytest-forked pytest-progress
      shell: bash
    - name: Run tests
      run: |
        if [ $DO_COVERAGE = "true" ]; then
          ${{ github.action_path }}/run_pytest.bash ${{ inputs.cover-packages }}
        else
          ${{ github.action_path }}/run_pytest.bash
        fi
      shell: bash
      env:
        TEST_PKG: ${{ inputs.tests }}
        DO_COVERAGE: ${{ inputs.coverage == 'true' }}
        EXTRA_OPTS: ${{ inputs.options }}
    - name: coverage
      run: |
        if [ $DO_COVERAGE = "true" ]; then
          coveralls --service=github || echo "::warning::Make sure you have used secrets.GITHUB_TOKEN, not secrets.COVERALLS_REPO_TOKEN"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.coveralls-token }}
        COVERALLS_FLAG_NAME: ${{ inputs.coveralls-flag-name }}
        COVERALLS_PARALLEL: ${{ inputs.coveralls-parallel }}
        DO_COVERAGE: ${{ inputs.coverage == 'true' }}
      shell: bash
