# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Check out and install SpiNNaker dependencies"
description: >
  Checks out (and optionally installs) SpiNNaker dependencies.
inputs:
  repositories:
    description: >
      The list of SpiNNaker dependencies to check out. Space-separated
    required: true
  install:
    description: Whether to install the dependency after checking it out
    required: false
    default: "false"
  preinstall:
    description: >
      Whether to pre-install the dependencies before running the installer
    required: false
    default: "false"
  requirements-filename:
    description: The name of the requirements file
    required: false
    default: requirements.txt
runs:
  using: composite
  steps:
    - run: |
        for repo in $DEPENDENCIES; do
          "$SPIN_GITCLONE" https://github.com/SpiNNakerManchester/$repo.git
        done
      shell: bash
      working-directory: .
      env:
        DEPENDENCIES: ${{ inputs.repositories }}
        SPIN_GITCLONE: ${{ github.action_path }}/gitclone.sh
    - run: |
        if [ $DO_INSTALL = "true" ]; then
          for repo in $DEPENDENCIES; do
            if [ -f "$repo/setup.py" ]; then
              echo "::group::Installing $repo"
              if [ $DO_PREINST = "true" -a -f $repo/$REQ_FILE ]; then
                (cd $repo && pip install -r $REQ_FILE)
              fi
              (cd $repo && exec python setup.py develop)
              echo "::endgroup::"
            fi
          done
        fi
      shell: bash
      working-directory: .
      env:
        DEPENDENCIES: ${{ inputs.repositories }}
        DO_INSTALL: ${{ inputs.install }}
        DO_PREINST: ${{ inputs.preinstall }}
        REQ_FILE: ${{ inputs.requirements-filename }}
