# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Check Copyrights
description: Uses Apache RAT to check for files without license declarations.
inputs:
  version:
    description: The version of Apache RAT to use
    required: false
    default: "0.14"
  mirror:
    description: The mirror of the Apache download site to get the library from
    required: false
    default: https://www.apache.org/dyn/closer.cgi?action=download&filename=
    # Another alternative: http://www.mirrorservice.org/sites/ftp.apache.org/
  allow_gpl:
    description: Flag to say gpl license are accepted
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Download
      run: $SUPPORT_DIR/download.bash
      shell: bash
      env:
        RAT_VERSION: ${{ inputs.version }}
        RAT_MIRROR: ${{ inputs.mirror }}
        SUPPORT_DIR: ${{ github.action_path }}
    - if ${{ inputs.allow_gpl }} == true
      name: "Check with GPL"
      run: |
        ant -e -q -f "$CFG" -lib "$LIB" rat
      shell: bash
      env:
        SUPPORT_DIR: ${{ github.action_path }}
        CFG: ${{ github.action_path }}/rat.xml
        LIB: ${{ github.action_path }}/apache-rat-${{ inputs.version }}
    - if ${{ inputs.allow_gpl }} == false
      name: "Check with no GPL"
      run: |
        ant -e -q -f "$CFG" -lib "$LIB" rat
      shell: bash
      env:
        SUPPORT_DIR: ${{ github.action_path }}
        CFG: ${{ github.action_path }}/rat_no_gpl.xml
        LIB: ${{ github.action_path }}/apache-rat-${{ inputs.version }}

branding:
  icon: search
  color: red
